const Data = {
  status: 'success',
  items: [
    {
      id: 1,
      title: 'Odger',
      price: 795,
      image: require('./Images/image2.jpg'),
      category: 'Chair',
      quantity: 100,
    },
    {
      id: 2,
      title: 'Nilsolle',
      price: 499,
      image: require('./Images/image3.jpg'),
      category: 'Bar Chair',
      quantity: 100,
    },
    {
      id: 3,
      title: 'Kyrre',
      price: 129,
      image: require('./Images/image4.jpg'),
      category: 'Stool Chair',
      quantity: 100,
    },
    {
      id: 4,
      title: 'Strandmon',
      price: 5990,
      image: require('./Images/image5.jpg'),
      category: 'Lounge Chair',
      quantity: 100,
    },
    {
      id: 5,
      title: 'Hokksund',
      price: 699,
      image: require('./Images/image6.jpg'),
      category: 'Side Table',
      quantity: 100,
    },
    {
      id: 6,
      title: 'Klubbfors',
      price: 4495,
      image: require('./Images/image7.jpg'),
      category: 'Sofa',
      quantity: 100,
    },
    {
      id: 7,
      title: 'Stockholm',
      price: 16955,
      image: require('./Images/image8.jpg'),
      category: 'nike',
      quantity: 100,
    },
    {
      id: 8,
      title: 'Leifarne',
      price: 545,
      image: require('./Images/image9.jpg'),
      category: 'Chair',
      quantity: 100,
    },
    {
      id: 9,
      title: 'Nordli',
      price: 1095,
      image: require('./Images/image10.jpg'),
      category: 'Side Table',
      quantity: 100,
    },
    {
      id: 10,
      title: 'Vedbo',
      price: 2495,
      image: require('./Images/image11.jpg'),
      category: 'Lounge Chair',
      quantity: 100,
    },
    {
      id: 11,
      title: 'Bingsta',
      price: 1995,
      image: require('./Images/image12.jpg'),
      category: 'Lounge Chair',
      quantity: 100,
    },
  ],
};

export default Data;
